#!/usr/bin/env bash
# Write a Bash script that transfers a file from our client to a server
if [ 0 -lt 3 ]; then
    echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
elif [ 0 == 3 ]; then
    scp -o StrictHostKeyChecking=no "" "@":~/
else
    scp -o StrictHostKeyChecking=no -i "" "" "@":~/
fi
