#!/usr/bin/env bash
# Install and configure HAproxy on your lb-01 server.
apt-get -y install software-properties-common
add-apt-repository -y ppa:vbernat/haproxy-1.5
apt-get -y update
apt-get install haproxy=2.0.\*
echo "backend web-backend
balance roundrobin
server 6270-web-01 18.210.17.251:80 check
server 6270-web-02 18.207.112.85:80 check
frontend http
bind *:80
mode http
default_backend web-backend
" >> /etc/haproxy/haproxy.cfg
service haproxy restart
