#!/usr/bin/env bash
# Install and configure HAproxy on your lb-01 server.
apt-get -y install software-properties-common
add-apt-repository -y ppa:vbernat/haproxy-1.5
apt-get -y update
apt-get install haproxy=2.6.0
echo "backend web-backend
balance roundrobin
server 6270-web-01 3.239.86.158:80 check
server 6270-web-02 34.239.166.29:80 check
frontend http
bind *:80
mode http
default_backend web-backend
" >> /etc/haproxy/haproxy.cfg
service haproxy restart
